[data_paths]
data : data
raw : raw
acc : raw_acc
time : time_windows
feat : features
zip : Activity_Recognition_Logs.zip
[result_paths]
config : config
model_file : model.yaml
results: results
scores : scores.json
[plots]
balance : balance.pdf
correlation : correlation.pdf
information : information.pdf
dropping : dropping.pdf
learning : learning.pdf
cross_validation : cross_validation.pdf
feature_importance : feature_importance.pdf
rocauc: roc_auc.pdf
