stages:
  preprocess:
    cmd: python3 pre_process.py
    deps:
    - pre_process.py
    - ${preprocessing.zip}
    outs:
    - ${preprocessing.root}
    params:
    - preprocessing.window
    - preprocessing.key
    - preprocessing.stride
  classify:
    cmd: python3 classify.py
    deps:
    - ${preprocessing.root}
    - classify.py
    plots:
    - ${result.path}/${plots.balance}
    # - ${result.path}/${plots.rank}
    - ${result.path}/${plots.confusion}
    - ${result.path}/${plots.classification}
    - ${result.path}/${plots.pca}
    # - ${result.path}/{plots.information}
    - ${result.path}/${plots.dropping}
    - ${result.path}/${plots.learning}
    - ${result.path}/${plots.cross_validation}
    # - ${result.path}/${plots.feature_importance}
    - ${result.path}/${plots.roc_auc}
    params:
    - pipeline
    - model
    - preprocessor
    - feature_selector
    metrics:
    - ${result.path}/${result.scores}
    outs:
    - ${result.path}/${result.cv}
  plot:
    cmd: dvc plots show -o ${result.path} --html-template ${result.path}/template.html
    deps:
    - classify.py
    - ${result.path}/${result.scores}
    outs:
    - ${result.path}/index.html
  score:
    cmd: dvc metrics show --all-branches --all-commits --md > ${result.path}/table.md
    deps:
    - ${result.path}/index.html
    - ${result.path}/${result.scores}
    outs:
    - ${result.path}/table.md