stages:
  preprocess:
    cmd: python3 pre_process.py
    deps:
    - pre_process.py
    - ${preprocessing.zip}
    outs:
    - ${preprocessing.root}
    params:
    - preprocessing.window
    - preprocessing.key
    - preprocessing.stride
  classify:
    cmd: python3 classify.py
    deps:
    - ${preprocessing.root}
    - classify.py
    plots:
    - ${result.path}/${plots.balance}
    # - ${result.path}/${plots.rank}
    - ${result.path}/${plots.confusion}
    - ${result.path}/${plots.classification}
    - ${result.path}/${plots.pca}
    # - ${result.path}/{plots.information}
    - ${result.path}/${plots.dropping}
    - ${result.path}/${plots.learning}
    - ${result.path}/${plots.cross_validation}
    # - ${result.path}/${plots.feature_importance}
    - ${result.path}/${plots.roc_auc}
    params:
    - pipeline
    - model
    - preprocessor
    - feature_selector
    metrics:
    - ${result.path}/${result.scores}
    - ${result.path}/${result.cv}
  plot:
    cmd: dvc plots show -o results
    deps:
    - classify.py
    - results
  score:
    cmd: dvc metrics show --all-branches --all-commits --md > results/table.md
    deps:
    - results/index.html
    - results/scores.json
  # server:
  #   cmd: cd results  && python -m http.server &
  #   deps:
  #   - results/index.html