model: sklearn.ensemble.RandomForestClassifier
params:
  n_estimators: 10
  max_depth: 1
data_paths:
  data: data
  raw: raw
  acc: raw_acc
  time: time_windows
  feat: features
  zip: Activity_Recognition_Logs.zip
result_paths:
  config: experiments
  model_file: model.yaml
  results: results
  scores: scores.json
plots:
  balance: balance.png
  rank: rank.png
  confusion: confusion.png
  classification: classification.png
  # dropping : dropping.png
  # learning : learning.png
  # cross_validation : cross_validation.png
  # feature_importance : feature_importance.png
  # rocauc: roc_auc.png
  # confusion : confusion.png
  # classification : classification.png
