preprocessing:
  root: data
  raw: raw
  acc: raw_acc
  mag: raw_mag
  time: time_windows
  feat: features
  zip: Activity_Recognition_Logs.zip
  key: mag
  window : 10
  stride : 2
  data_file : data.npz
  train_key : train
  test_key : test
pipeline: # Determine the sklearn pipeline order
- preprocessor
- feature_selector
- model
model: # Model
  name : sklearn.ensemble.RandomForestClassifier
  n_estimators : 100
  max_depth : 10
preprocessor: # Centers and Scales
  name : sklearn.preprocessor.StandardScaler
  with_std : True
  with_mean : True
feature_selector: # Selects Features
  name : sklearn.feature_selection.SelectKBest
  k: 100
sample: # Samples the Data
  name: data/features/train_data.npz
  shuffle : True
  random_state : 42
  train_size : 2500
  test_size : 0
  stratify : True
result: # result path
  path: results
  test: data/features/test_data.npz
  scores: scores.json
search:
  name : sklearn.model_selection.GridSearchCV
  refit : True
grid:
  n_estimators : [10, 20, 30]
  k : [10, 20, 30]
plots: #plots
  balance: balance.png
  rank: rank.png
  confusion: confusion.png
  classification: classification.png
  pca : pca.png
  # dropping : dropping.png
  # learning : learning.png
  # cross_validation : cross_validation.png
  # feature_importance : feature_importance.png
  # rocauc: roc_auc.png
  # confusion : confusion.png
  # classification : classification.png
